"""add prevent_duplicate_scans to receipt_definitions

Revision ID: 38b6264acc39
Revises: a7aec50bc2aa
Create Date: 2026-09-04 08:47:04.633839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b6264acc39'
down_revision: Union[str, Sequence[str], None] = 'a7aec50bc2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('receipt_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'prevent_duplicate_scans', sa.Boolean(), nullable=False, server_default=sa.false()
        ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_definitions', schema=None) as batch_op:
        batch_op.drop_column('prevent_duplicate_scans')

    # ### end Alembic commands ###
