"""baseline schema

Revision ID: a7aec50bc2aa
Revises: 
Create Date: 2026-07-27 10:51:46.099438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7aec50bc2aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('receipt_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('template_tokens', sa.JSON(), nullable=False),
    sa.Column('part_number', sa.String(length=100), nullable=True),
    sa.Column('customer_part_number', sa.String(length=100), nullable=True),
    sa.Column('part_description1', sa.String(length=200), nullable=True),
    sa.Column('part_description2', sa.String(length=200), nullable=True),
    sa.Column('drawing_number', sa.String(length=100), nullable=True),
    sa.Column('drawing_date_text', sa.String(length=50), nullable=True),
    sa.Column('manuf_code', sa.String(length=50), nullable=True),
    sa.Column('ka_revision_level', sa.String(length=20), nullable=True),
    sa.Column('generation_status', sa.String(length=20), nullable=True),
    sa.Column('product_designation', sa.String(length=100), nullable=True),
    sa.Column('duns', sa.String(length=20), nullable=True),
    sa.Column('bg_nr', sa.String(length=20), nullable=True),
    sa.Column('quantity_text', sa.String(length=20), nullable=True),
    sa.Column('serial_min', sa.Integer(), nullable=True),
    sa.Column('serial_max', sa.Integer(), nullable=True),
    sa.Column('timestamp_policy', sa.String(length=30), nullable=False),
    sa.Column('frozen_timestamp', sa.DateTime(), nullable=True),
    sa.Column('companion_receipt_id', sa.Integer(), nullable=True),
    sa.Column('companion_required', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['companion_receipt_id'], ['receipt_definitions.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scan_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_definition_id', sa.Integer(), nullable=False),
    sa.Column('started_by_user_id', sa.Integer(), nullable=False),
    sa.Column('operator_number', sa.String(length=50), nullable=False),
    sa.Column('line_number', sa.String(length=50), nullable=False),
    sa.Column('plain_line_number', sa.String(length=50), nullable=True),
    sa.Column('batch_label', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_definition_id'], ['receipt_definitions.id'], ),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_session_id', sa.Integer(), nullable=False),
    sa.Column('receipt_definition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('scanned_value', sa.String(length=500), nullable=False),
    sa.Column('result_ok', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=50), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_definition_id'], ['receipt_definitions.id'], ),
    sa.ForeignKeyConstraint(['scan_session_id'], ['scan_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_session_id', sa.Integer(), nullable=False),
    sa.Column('primary_event_id', sa.Integer(), nullable=False),
    sa.Column('companion_event_id', sa.Integer(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['companion_event_id'], ['scan_events.id'], ),
    sa.ForeignKeyConstraint(['primary_event_id'], ['scan_events.id'], ),
    sa.ForeignKeyConstraint(['scan_session_id'], ['scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_units')
    op.drop_table('scan_events')
    op.drop_table('scan_sessions')
    op.drop_table('receipt_definitions')
    op.drop_table('users')
    # ### end Alembic commands ###
