"""add auto_generate_batch_number and line_batch_counters

Revision ID: a7d453f2d44f
Revises: 38b6264acc39
Create Date: 2026-09-07 08:06:49.028831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d453f2d44f'
down_revision: Union[str, Sequence[str], None] = '38b6264acc39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('line_batch_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plain_line_number', sa.String(length=50), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plain_line_number')
    )
    with op.batch_alter_table('receipt_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'auto_generate_batch_number', sa.Boolean(), nullable=False, server_default=sa.false()
        ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_definitions', schema=None) as batch_op:
        batch_op.drop_column('auto_generate_batch_number')

    op.drop_table('line_batch_counters')
    # ### end Alembic commands ###
